service: notifier
provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-northeast-2
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 5
  environment:
    CHANNEL_SECRET: ${env:CHANNEL_SECRET}
    CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}
    DB_HOST: ${env:DB_HOST}
    DB_PASSWORD: ${env:DB_PASSWORD}

plugins:
  - serverless-webpack

functions:
  webhook:
    handler: src/handler.webhook
    events:
      - httpApi: POST /webhook
  noti:
    handler: src/handler.noti
    events:
      - httpApi: POST /noti/{token}
